version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: teastore
      POSTGRES_USER: teastore
      POSTGRES_PASSWORD: teastore
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./apps/backend
    env_file: ./apps/backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    depends_on: [db, redis]

  frontend:
    build: ./apps/frontend
    env_file: ./apps/frontend/.env.local
    ports: ["3000:3000"]
    command: npm run dev
    depends_on: [backend]

volumes:
  pgdata:

