[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://innerveda-tea-api.herokuapp.com/api/:splat"
  status = 200
  force = true

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://innerveda-tea-api.herokuapp.com"
  NEXT_PUBLIC_SITE_URL = "https://innerveda.netlify.app"
  NEXT_PUBLIC_USE_MOCK = "0"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://innerveda-tea-api.herokuapp.com"
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--innerveda.netlify.app"
  NEXT_PUBLIC_USE_MOCK = "0"
